Menu de navegacion para el dashboard de trading
tvgni/tradingoperations-client pull request #2
Opened 2023-05-09 04:33 UTC by dgaleano

2023-05-28 20:38 UTC, fzamora91 reviewed
Nueva paginas para el dashboard con componentes para navegacion

2023-05-29 22:56 UTC, lcorozco10 requested changes
Te deje unos comentarios sencillos felix

2023-05-29 22:56 UTC, lcorozco10 commented on app/dashboard/NavigationList.tsx
> +  return <Link href="/DashBoard/Usuarios">Usuarios</Link>;
Creo qye deberian ser en minusculas el valor del atributos href

2023-05-29 22:56 UTC, lcorozco10 commented on app/dashboard/NavigationList.tsx
> +  return <Link href="/DashBoard">Dashboard</Link>;
Creo qye deberian ser en minusculas el valor del atributos href

2023-05-29 22:56 UTC, lcorozco10 commented on app/dashboard/NavigationList.tsx
> +  return <Link href="/DashBoard/Informes">Informes</Link>;
Creo qye deberian ser en minusculas el valor del atributos href

2023-05-29 22:56 UTC, lcorozco10 commented on app/dashboard/NavigationList.tsx
> +          {/*<Item render={renderCustomItemDashboard} icon={'product'}></Item>
eliminar codigo comentado

2023-05-29 22:56 UTC, lcorozco10 commented on app/dashboard/Navigations.tsx
> +    //window.redirect.open('http://localhost:3000/DashBoard/Profile', '_blank');
eliminar codigo comentado

2023-05-29 22:56 UTC, lcorozco10 commented on app/dashboard/menus.tsx
> +  { id: 1, text: 'Dashboard', icon: 'product' },
eliminar codigo comentado

2023-05-30 03:28 UTC, lcorozco10 approved these changes

2023-05-30 05:17 UTC, fzamora91 approved these changes

2023-05-30 05:18 UTC, merged